version: "3"

services:
  memento:
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/memento:v2
    volumes:
      - ./storage:/storage
      - ./drop:/drop
    ports:
      - "8000:80"